{
 "title": "Meshcore",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Mesh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Neighbors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SNR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk by(neighbor_pubkey)(10, sort_desc(meshcore_neighbor_snr_db))",
     "legendFormat": "{{neighbor_name}}"
    }
   ]
  },
  {
   "title": "Contacts and Neighbors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "targets": [
    { "expr": "meshcore_contacts_total", "legendFormat": "{{target}} Contacts" },
    {
     "expr": "meshcore_neighbors_zero_hop_total",
     "legendFormat": "{{target}} Neighbors"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Battery Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "meshcore_battery_percent", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "meshcore_battery_voltage_volts", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Status Metrics",
   "type": "stat",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meshcore_status_value", "legendFormat": "{{field}}" }
   ]
  }
 ]
}